### ISSUE TITLE
It's will support nginx-1.6.2 ?

### ISSUE THREAD

**Issue by wangfakang** [0xc0dec/ustats#7]
hi @0xc0dec It's a good project. I've been study nginx on monitoring of upstream, `ustats` is three years was no updated. It's will have support high version of the nginx or have any other good solution to replace? 

Thank you.

**Comment by 0xc0dec** [comment]
Hi @wangfakang,

ustats is indeed abandoned and I have no idea what projects out there have similar functionality. Haven't been following nginx-related news for quite a long time. Sorry.

**Comment by wangfakang** [comment]
Oh,Thank you for your prompt reply.
